language: node_js

node_js:
  - stable

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run lint
  - npm run coveralls

after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
